### ISSUE TITLE
label-fast: Keep zoom feature improvement

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#103]
Keep zoom feature is very useful.
If you remember I suggested you this feature in very early versions of RectLabel.
Now I'm suggesting another related feature.

It would be useful to have another setting (maybe a two options only) related to keep-zoom to specify if while keeping the zoom from previous image, when going to next image, we want to center this new one inside the window or if we also want to keep previous x,y position of the image.

Hope I explained well.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
For the "Maintain zoom" feature, you want 2 options.
1. The position should be the center of the new image.
2. The position should be the same as the previous image.
It looks that if we could implement 2., It would be enough for labeling video frames.
Why do you need 1.?

**Comment by mentezar** [comment]
My main need is the option 2 you mentioned.
Option 1 is mainly for "backward compatibility" and for people that don't want to reuse previous image position for next image.

**Comment by ryouchinsa** [comment]
Improved so that "maintain zoom" maintains zoom and position.

The new update version 2.76 was released.
To show the new update on Mac App Store, press command + R to reload.

![スクリーンショット 2019-06-01 11 57 19](https://user-images.githubusercontent.com/1954306/58743044-8174f580-8465-11e9-8bf2-8736489d3ad5.png)
