### ISSUE TITLE
Add statusbar

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#104]
It's useful to have a status bar showing informations on actual mouse position, like OpenCV's `imshow` function with QT backend (also with colored text):

![imshow status bar](https://cdn-images-1.medium.com/max/1600/1*aQgq3zxr5TNpCzU3yCgRDA.png)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

For the box size, it is relevant to the receptive field size of your neural network model.
Your model might train boxes greater than 32px, 48px, or 64px.
So that we understand the box size is important for labeling.

RectLabel is showing the box size when you create and edit the box.

![スクリーンショット 2019-06-06 20 29 52](https://user-images.githubusercontent.com/1954306/59029897-745b6a80-889a-11e9-829d-e69b47971f39.png)

If you need to know the pixel color, you can use the color picker tool.

![スクリーンショット 2019-06-06 20 31 23](https://user-images.githubusercontent.com/1954306/59029906-79b8b500-889a-11e9-9e07-9bfb6b338e92.png)

For the mouse position, is it relevant to training neural network?

**Comment by mentezar** [comment]
- it would be useful to reshow box size also when selecting an already created box
- ok for color picker tool. sorry, didn't noticed it.
- the mouse position in real-time is not relevant for training neural networks, but as of RectLabel is very fast, it should be used to get some basic infos in real-time instead of opening slower and overkill tools like Gimp.

**Comment by ryouchinsa** [comment]
For the box size, in the next update, is shown when you select the box.

For mouse position, we do not think the feature is necessary for RectLabel.
As you might know, we are working on iPad version, too.
We want to focus on features which could be used on iPad, too.
Hope you could understand.
