### ISSUE TITLE
annotation folder not read again

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#111]
I started creating annotations on my mac. I annotated first 100 images of 500. `annotations` folder was created.
I copied both `annotation` folder and `images` folder to my coworker's mac and she continued to annotate.

Now I copied back the updated `annotation` folder to my mac, in the same original path.
I opened RectLabel and it didn't show the annotations made by the coworker. It "remained" to my annotations status.
I had to `File => Close folder` and reopen again and new annotations are showed again.

I think it's a bug, like some caching somewhere.

Correct behaviour should be to re-read all `annotations` folder (of previous working directories) every time I open RectLabel.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You renamed the original folder and copied the same named folder from another pc.

1. RectLabel cannot access to the folder which is not opened by users even if the folder path is the same.

2. We are using this api to resolve the bookmarked folder path.
https://developer.apple.com/documentation/foundation/nsurl/1572035-urlbyresolvingbookmarkdata
Basically this api can open the folder even if you renamed the folder.
If you renamed the folder and launch RectLabel again, RectLabel opens the renamed folder.
This might be confusing for our users.
We would change so that if you renamed the folder, we detect the original folder does not exist as the same name and show the bookmark error dialog when you launch RectLabel.

**Comment by mentezar** [comment]
ok. Maybe the API, internally keeps a reference by inode instead of folder name.
Thanks.

**Comment by ryouchinsa** [comment]
The new update version 2.81 was released.
To show the new update on Mac App Store, press command + R to reload.

- Fixed that capitalized object names do not match with objects table items.
- Improved so that when you rename the current folder and launch RectLabel, we show the bookmark error dialog and not to open the new-named folder.
