### ISSUE TITLE
No colors for rectangles

### ISSUE THREAD

**Issue by Peewee1963** [ryouchinsa/Rectlabel-support#115]

**Comment by Peewee1963** [comment]
In the new version, no different colors for different objects are shown anymore.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
We had the same report from another user.

Fixed that capitalized object names do not match with objects table items.

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 2.81 was released.
To show the new update on Mac App Store, press command + R to reload.

- Fixed that capitalized object names do not match with objects table items.
- Improved so that when you rename the current folder and launch RectLabel, we show the bookmark error dialog and not to open the new-named folder.
