### ISSUE TITLE
Load label from previous image and position/zoom

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#117]
When I have the option `Maintain zoom and position` enabled and I use `Load labels from previous image` the zoom and position are not preserved.
The image goes out of the canvas. I have to zoom-out a lot and I start to see it in the lower left (to middle) part of the canvas.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

- Improved the problem when you use "Load labels from prev image" and "Maintain zoom and position" at the same time.
- Improved so that "Load labels from prev image" does not show the confirmation dialog.

The new update version 2.83 was released.
To show the new update on Mac App Store, press command + R to reload.
