### ISSUE TITLE
Brush tool: remember last size

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#119]
Every time I launch RectLabel the brush tool resets its size to `50`.
It would be nice to remember last set size.

**Comment by ryouchinsa** [comment]
The new update version 2.86 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved so that pixels dialog remembers the position when you launch RectLabel.
- Improved so that pixels dialog remembers the brush size when you launch RectLabel.
- Improved so that changing brush size continuously changes the value during dragging the slider.
