### ISSUE TITLE
Brush tools size slider

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#120]
Please make the slider updating the text label in "real-time".
Now I have to move the slider, think where right position should be, release mouse, check the size and correct if wrong. It's a loss of time.

PS: Actually the only way to be precise is to give focus to the slider and uso keyboard's left/right arrow but overall it's not an optimized workflow.

**Comment by mentezar** [comment]
It also seems that if I go to next image and go back to previous image now the brush pointer appears and works

**Comment by ryouchinsa** [comment]
The new update version 2.86 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved so that pixels dialog remembers the position when you launch RectLabel.
- Improved so that pixels dialog remembers the brush size when you launch RectLabel.
- Improved so that changing brush size continuously changes the value during dragging the slider.

> It also seems that if I go to next image and go back to previous image now the brush pointer appears and works

Please continue discussing here.  https://github.com/ryouchinsa/Rectlabel-support/issues/118
