### ISSUE TITLE
Pixel and brush panel position

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#121]
It would be nice to remove the floating `Pixel` panel because it's annoying and forces to move it away many times when drawing pixels.
Please put it fixed above the objects panel (right). Someway like a classical multi-purpose “option panel“ that you can use to display various options of the current selected tool/annotation-type options.

**Comment by ryouchinsa** [comment]
The new update version 2.86 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved so that pixels dialog remembers the position when you launch RectLabel.
- Improved so that pixels dialog remembers the brush size when you launch RectLabel.
- Improved so that changing brush size continuously changes the value during dragging the slider.
