### ISSUE TITLE
Labels fast - Load labels from prev image

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#122]
For the functionality `Edit -> Load labels from prev image` please add a checkbox in `Settings`, tab `Label fast` to avoid the confirmation box.

Thanks

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

- Improved the problem when you use "Load labels from prev image" and "Maintain zoom and position" at the same time.
- Improved so that "Load labels from prev image" does not show the confirmation dialog.

The new update version 2.83 was released.
To show the new update on Mac App Store, press command + R to reload.
