### ISSUE TITLE
Disappearing lines on high zoom levels

### ISSUE THREAD

**Issue by dilpreetsingh** [ryouchinsa/Rectlabel-support#136]
Hey,

There seems to be an issue where the polygon lines start glitching in and out when zoomed in quite far. I've attached a screen recording of what i mean: https://www.dropbox.com/s/ryihh8jomdy4y83/rectlabel-zoom-issue.mov?dl=0

It happens on angled lines, and not on simple straight ones. So more an issue with polygons than a rectangle.

I'm on Version 2.90 (2.90)

Thanks

**Comment by dilpreetsingh** [comment]
Just noticed that the issue is worse when dealing with long and thin polygons. To recreate, draw a 45 degree rotated rectangle that starts from top-left of image to the bottom-right. Now zoom into the top-left, you'll see that not only do the lines appear/disappear, the thickness of the lines also starts changing randomly.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
We could reproduce the problem in our environment.
We will let you know when we could find the way to fix the problem.

**Comment by ryouchinsa** [comment]
It looks that the problem happens when the long line is angled and high zoom.
For boxes and cubic bezier, it does not happen.
For drawing boxes and polygons, we are using the same code.
We do not know the essential reason to fix it.

To prevent the glitching, you can add points between polygon points.
Because adding points reduces the line length.

We can add an option to draw extra points between polygon points to reduce glitching.

**Comment by dilpreetsinghaimi** [comment]
I don't remember seeing this issue in earlier versions (before the new smooth zoom had been implemented). Is it new drawing code?

**Comment by ryouchinsa** [comment]
We checked the old version which did not support the smooth zoom for large images.
The same problem existed.
And, we have not changed the drawing code for polygons.

**Comment by dilpreetsingh** [comment]
Ahh, i must never have zoomed in to that level before! Thanks for checking.
A shortcut to add points between polygon points would be useful to have.

**Comment by ryouchinsa** [comment]
- Added "Draw extra points to reduce glitching when high zoom" on the settings dialog.
It looks that the problem happens when the long line is angled and high zoom.
For boxes and cubic bezier, it does not happen.
To prevent the glitching, you can add points between polygon points.
Because adding points reduces the line length.

The new update version 2.91 was released.
To show the new update on Mac App Store, press command + R to reload.
