### ISSUE TITLE
unable to create box

### ISSUE THREAD

**Issue by Tharwa86** [ryouchinsa/Rectlabel-support#155]
Unable to create box like usual, now it takes me longer and need to click 4 times until the box appear, And that's was happened after the last update I got it from rectlabel .

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

Clicking 4 points can draw a perfect box.
Because annotators can focus on xmin, xmax, ymin, and ymax of the object.
But dragging a box needs adjusting the shape after drawing.

Extreme clicking for efficient object annotation
https://arxiv.org/abs/1708.02750

To obtain the previous version, please send an e-mail to support@rectlabel.com.
