### ISSUE TITLE
Bag with orientation and coordinates

### ISSUE THREAD

**Issue by GLKonstantin** [ryouchinsa/Rectlabel-support#167]
Программа отображает ориентацию изображения согласно метки exif файла, а вот размеченные координаты сохраняет согалсно ориентации оригинала, таким образом в обучение могут попасть неверно размеченные данные что искажают обучение. Такое может произойти если вы вручную повернули изображение перед тем как обработать его в RectLabel. Эта статья описывает проблему и решение: https://habr.com/ru/post/471112/

The program loads the image orientation according to the exif label in the file, and saves the coordinates relative to the original image. As a result, incorrectly marked data ends up in machine learning. This article describes the problem and solution: https://habr.com/ru/post/471112/

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Which neural network tool are you using to train your object detection model?

sizeMismatch error on detectron2
https://github.com/facebookresearch/detectron2/issues/863

RectLabel and macOS Viewer show images with Exif orientation flags in the same way.
According to the Exif orientation flag, each image is rotated and shown in the front orientation.
So that the annotation file on RectLabel assumes that the image is rotated and shown in the front orientation.
https://rectlabel.com/help#open_both_folders

EXIF Orientation-flag example images
https://github.com/recurser/exif-orientation-examples

EXIF Orientation Handling Is a Ghetto
https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

**Comment by GLKonstantin** [comment]
Sorry friend.
That's my fault. I cut the image according to the * .json coordinates for create ml and got the wrong places in the coordinates. I programmatically opened the image and did not watch exif.
 
I am really looking forward to the ipad application and will definitely buy it.
 
 
 
 
 
  
>Суббота, 30 мая 2020, 4:57 +03:00 от Ryo Kawamura <notifications@github.com>:
> 
> 
>Thanks for writing the issue.
>Which neural network tool are you using to train your object detection model?
>sizeMismatch error on detectron2
>facebookresearch/detectron2#863
>RectLabel and macOS Viewer show images with Exif orientation flags in the same way.
>According to the Exif orientation flag, each image is rotated and shown in the front orientation.
>So that the annotation file on RectLabel assumes that the image is rotated and shown in the front orientation.
>https://rectlabel.com/help#open_both_folders
>EXIF Orientation-flag example images
>https://github.com/recurser/exif-orientation-examples
>EXIF Orientation Handling Is a Ghetto
>https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Левицкий Константин Аркадьевич.

т.моб.  8(903)751-87-01
89037518701@mail.ru

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
