### ISSUE TITLE
Pixels and superpixel areas not showing

### ISSUE THREAD

**Issue by hjedwardkim** [ryouchinsa/Rectlabel-support#177]
Hello, my colleague has a problem in that whenever he tries to select "Label Pixels," RectLabel crashed. After a week, it seemed to not crash anymore but the pixels and superpixel areas do not appear anymore, even when cycling through "Hide Pixels" and "Hide Superpixels."

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

To reproduce the problem in our environment, could you give us the image and annotation file which does not work with pixels tools?

**Comment by hjedwardkim** [comment]
[Archive.zip](https://github.com/ryouchinsa/Rectlabel-support/files/5429931/Archive.zip)

Hello, I have attached an example image with some test annotations that my colleague has created with different tools. It seems that polygon and bounding boxes work but pixels and superpixels do not appear. I cannot replicate this problem on my computer however. Could this be a user error or a bug?

**Comment by ryouchinsa** [comment]
Thanks for the example data.

It looks that a png file for the pixels object is missing.
We cannot reproduce the problem.
After opening the image and annotation file, we can draw pixels using brush and superpixel tools.

Could you record the video of the problem using QuickTime?
What happens if you resize the image from 5280px to a smaller size?
You can find crash logs here. "~/Library/Logs/DiagnosticReports/".

**Comment by hjedwardkim** [comment]
Hi, I will test those in the following week with my colleague. In the meantime, here's a recording of the issue.

[Uploading bug-video.mov.zip…]()

**Comment by ryouchinsa** [comment]
Thank you.

The video link is not working.
Please attach the video.

Again, please make sure that attached annotation folder did not include the png mask image.
There should be "DJI_0013_pixels0.png" in the folder.
So that there are no pixels mask on RectLabel.

If RectLabel crashes again, please send the crash log.
"~/Library/Logs/DiagnosticReports/"

**Comment by hjedwardkim** [comment]
Hello,

After a closer inspection, we found that _pixels0.png wasn't being generated, hence its absence in the folder sent. However, we also found that updating the software fixed the issue. I suppose we can close this as the problem is solved.
