### ISSUE TITLE
Core ML predictions include confidence score

### ISSUE THREAD

**Issue by atomicguy** [ryouchinsa/Rectlabel-support#178]
Would it be possible to add confidence score to label predictions from a Core ML model?

I have a Core ML model to predict object detection bounding boxes. I ran it on a set of images I have, but some low confidence predictions are included in the results.

Could it be possible to include the confidence in the predictions so I can filter them after they have been run? Or an interface to choose confidence threshold before prediction?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

For object detection models, you can set the 'confidence_threshold'.
https://rectlabel.com/help#load_coreml
https://github.com/ryouchinsa/Rectlabel-support/blob/master/coreml_yolov3.py

`coreml_model.user_defined_metadata['confidence_threshold'] = '0.25'`

**Comment by ryouchinsa** [comment]
To edit the 'confidence_threshold' for existing models, you can use this code.
```
import coremltools
import sys

model_path = sys.argv[1]
coreml_model = coremltools.models.MLModel(model_path)
coreml_model.user_defined_metadata['confidence_threshold'] = '0.25'
coreml_model.save(model_path)
```

Currently If you need our support to fix this problem, please let us know.

**Comment by atomicguy** [comment]
I tried the code you suggested. I also tried adjusting the `nonMaximumSuppression.confidenceThreshold` value for my model. Neither seemed to make any change on the results when predicting with RectLabel

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

Both ways are working for our Turi Create and YOLO models.

How did you train your model?
Please tell us the version of Turi Create or Create ML.
https://apple.github.io/turicreate/docs/userguide/object_detection/export-coreml.html

**Comment by atomicguy** [comment]
I trained the model with Create ML 2.0 (53.1).
It's an object detection model, which I think means it's YOLO under the hood.

Predictions in Create ML show three 100% and one 60% prediction.
When I run it in RectLabel after setting the confidence to 0.90, all 4 predictions are captured.
<img width="1016" alt="Screen Shot 2020-12-03 at 11 26 33 AM" src="https://user-images.githubusercontent.com/395176/101077987-69020180-355a-11eb-8727-4d665a67f0fc.png">

**Comment by ryouchinsa** [comment]
Thanks for the details.

We found that 'confidence_threshold' works when include_non_maximum_suppression=False.
`model.export_coreml('MyDetector.mlmodel', include_non_maximum_suppression=False)`

We improved so that 'confidence_threshold' works when include_non_maximum_suppression=True.
`model.export_coreml('MyDetector.mlmodel', include_non_maximum_suppression=True)`

We think that Create ML saves the Core ML model as  include_non_maximum_suppression=True.
https://apple.github.io/turicreate/docs/api/generated/turicreate.object_detector.ObjectDetector.export_coreml.html

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 3.04.2 was released.
To show the new update on Mac App Store, press command + R to reload.

- Fixed so that 'confidence_threshold' is used for the model exported with non-maximum suppression.
- Added undo/redo for "Process the image using Core ML model".
- Improved so that the spinner is shown during processing.
- Improved so that backing up images/annotations is done in async.

We trained raccoon dataset using Core ML and confirmed that we can change the 'confidence_threshold' using the python script above.
https://public.roboflow.com/object-detection/raccoon

Let us know your feedback.

**Comment by atomicguy** [comment]
Now when I try to load a model it says "Model Metadata description is empty."

Attached is my model and an example picture.

[example.zip](https://github.com/ryouchinsa/Rectlabel-support/files/5657122/example.zip)

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

It is not an error.
Literally just the Model Metadata description is empty in the model.
RectLabel shows the description when finished loading the model.

1. You can set the description through python script.

```
import coremltools
import sys

model_path = sys.argv[1]
coreml_model = coremltools.models.MLModel(model_path)
coreml_model.short_description = "PairDetectorThresh.mlmodel"
coreml_model.user_defined_metadata['confidence_threshold'] = '0.9'
coreml_model.save(model_path)

```

2. You can set the description on Create ML when you create the project.

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1954306/101464588-2be6a680-3982-11eb-833e-2aa10537ce6c.png">

Let us know your feedbakck.

**Comment by atomicguy** [comment]
Awesome, that worked! I think I missed the message before because it didn't show up in dark mode prior to this update.
