### ISSUE TITLE
Will you consider adding non rectangular shapes (quadrangles for example)?

### ISSUE THREAD

**Issue by xvolks** [ryouchinsa/Rectlabel-support#18]
I may use [EAST](https://github.com/argman/EAST) for a future project and I'll need to label non rectangular zones in image.

Do you think this type of labeling will fit in RectLabel?

**Comment by ryouchinsa** [comment]
We had a similar request before.

> Do Rectlabel support rotating the bounding box? https://github.com/ryouchinsa/Rectlabel-support/issues/6.

We did not know about the use case like EAST.

![output](https://user-images.githubusercontent.com/1954306/29398621-93fb6a16-8360-11e7-892c-3c908781f583.png)

Yes, in our roadmap, we are going to implement the bezier spline curve to draw contours for medical use cases and image segmentation.

On the way to the bezier spline curve,  the quadrangles would be implemented, too.

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

RectLabel 1.50
- added rotate box mode
- added drawing polygon mode
- added drawing cubic bezier mode
- added convert JSON files to XML files menu
- removed JSON file format support
- removed smart guides

![draw](https://user-images.githubusercontent.com/1954306/33141127-88f17ca0-cff5-11e7-87e3-9c9634a4a9ae.jpg)

**Comment by xvolks** [comment]
Why removing JSON format and smart guides ?
Are these features definitely gone ?

**Comment by ryouchinsa** [comment]
HI, 
Some users have troubles for the JSON format because the format cannot be used in TensorFlow directly. https://github.com/ryouchinsa/Rectlabel-support/issues/31

There are many converters from the PASCAL VOC format to other formats.
So that we decided to focus on the PASCAL VOC format.

At the beginning of our development, we thought smart guides would be useful to draw boxes in a beautiful way.
But when we draw many boxes and points of polygon in the image, it looks smart guides are not effective in terms of productivity.

RectLabel 1.50 was released.

**Comment by fastlater** [comment]
@ryouchinsa  Are rotated bounding boxes valid for training the tensorflow object detection api?

**Comment by ryouchinsa** [comment]
Hi,

It looks the tensorflow object detection api does not accept the rotated box or polygon yet.
https://stackoverflow.com/questions/47149601/tensorflow-object-detection-api-using-polygon-labeled-dataset
https://github.com/tensorflow/models/issues/1835
