### ISSUE TITLE
performRequests error on DepthPrediction CoreML model 

### ISSUE THREAD

**Issue by yongja-jayong** [ryouchinsa/Rectlabel-support#184]
I loaded [FCRN-DepthPrediction model](https://developer.apple.com/machine-learning/models/) which is provided from Apple developer site.
And when I processed an image, performRequest error occurs because of an unknown exception.
It seems like the other models on Apple developer site are working well. Maybe it could be because of the model file itself...

![image](https://user-images.githubusercontent.com/39395433/125772634-53d94130-d616-407b-a176-6dcdf1aa68bc.png)

It's Rectlabel(3.05.5) and Macbook(16-inch, 2019) BigSur(11.2.3).

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We have not implemented to decode the depth image generated by FCRN-Depth model yet.
We will implement and submit the new update soon.

In our environment, at this moment, the new decoding module started working.

![スクリーンショット 2021-07-17 8 06 34](https://user-images.githubusercontent.com/1954306/126016583-b47e8bf8-2033-4219-9e8b-4806e914db38.png)

![スクリーンショット 2021-07-17 8 06 40](https://user-images.githubusercontent.com/1954306/126016597-665d9270-2fd7-429d-884f-96956c514217.png)

**Comment by ryouchinsa** [comment]
The new update version 3.05.7 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved Core ML features so that you can process images using FCRN-Depth model and save depth images.
- Fixed the "Show depth channel" problem that the depth layer is not shown after changing the image. 

To toggle the depth layer alpha, use "Show depth channel" on View menu.

**Comment by yongja-jayong** [comment]
Thank you so much for your quick reply and update. 
Now it works perfectly fine 😄
