### ISSUE TITLE
Rotate images to ensure consistent orientation

### ISSUE THREAD

**Issue by jimjam-slam** [ryouchinsa/Rectlabel-support#187]
Hi there! Love using RectLabel. I've labelled a bunch of images, but it wasn't  until I went to train my model that I realised the fact half the images are portrait and half are landscape might be problematic for the model (there isn't necessarily a natural orientation for the images themselves, so I didn't check at the time). It'd be great if RectLabel had the ability to rotate some of the images so that they were all portrait or all landscape (while transforming existing labels to their new coordinates in the rotated images)!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

On RectLabel, each image is rotated and shown in the front orientation.
So that the annotation file on RectLabel assumes that the image is rotated and shown in the front orientation.
https://rectlabel.com/help#open_both_folders

To convert all images to the front orientation, please use Export menu -> Resize all images feature.
Set "Image size max" empty, then images are saved in the front orientation with the same image size.

Let us know your opinion.

**Comment by rensa** [comment]
Hi there! Thanks for engaging so quickly. I gave the "Resize all images command" option a crack, but it doesn't seem to have had any material effect on the images' sizes.

In my case, it's not that some of the training images have been pre-rotated—rather, the images were taken nearly directly face down, and so my phone (which took the images) has chosen different orientations for them based on minor differences in camera orientation.

The images are all the same size, but I'd like to ensure that they're either all landscape or all portrait.

>

**Comment by ryouchinsa** [comment]
Let us explain the current situation we understand using images.

Here are some exif-oriented images.
https://github.com/recurser/exif-orientation-examples

We use Portrait_1.jpg(Portrait 1200x1800) and Portrait_6.jpg(Landscape 1800x1200).

On RectLabel, both images are shown in the front orientation.
So that image size in each annotation file is shown as 1200x1800.

The problem might happen when you train using python modules.
Because the image size in each annotation file is different from the actual image size.

We checked for both pillow and skimage.
For pillow, before resizing,
Portrait_1.jpg -> 1200x1800
Portrait_6.jpg -> 1800x1200
after resizing,
Portrait_1.jpg -> 1200x1800
Portrait_6.jpg -> 1200x1800
So that each image size matches the image size in each annotation file.

But for skimage, it did not work.
Before resizing,
Portrait_1.jpg -> 1800x1200
Portrait_6.jpg -> 1800x1200
after resizing,
Portrait_1.jpg -> 1800x1200
Portrait_6.jpg -> 1800x1200
The image size should be changed to 1200x1800.

Could you explain your situation using some images?
If you cannot show your images here, please send a few images to support@rectlabel.com.

**Comment by ryouchinsa** [comment]
When you use Export menu -> Resize all images feature, all image are overwritten using opencv methods imread() and imwrite(), then each image is rotated to the front orientation and the exif orientation tag is removed from the jpg file.

On RectLabel, as debugging, we can use NSImage -> initWithDataIgnoringOrientation() method not to rotate image automatically according to the exif orientation tag.

Before resizing, Portrait_6.jpg is shown in the landscape orientation and the annotation does not match.

![before_resizing](https://user-images.githubusercontent.com/1954306/133533183-12db1c9d-e114-467c-a092-5ea67bf7923c.png)

After resizing, Portrait_6.jpg has no exif orientation tag so that the image is shown in the front orientation and the annotation matches.

![after_resizing](https://user-images.githubusercontent.com/1954306/133533192-89f66987-090d-4c18-952f-b3c7477fb9ac.png)

We think Export menu -> Resize all images can convert all exif oriented images so that each image does not have any exif orientation tag and shown in the front orientation.
When you train on python modules, the image size in the annotation file matches with the actual image size.

Let us know your opinion.

For skimage, we read the issue below and it looks that pillow is recommended.

skimage.io rotates the image
https://github.com/scikit-image/scikit-image/issues/3150

"Personally, I think this is better handled either down in Pillow, or in imageio.
scikit-image having their own additional features for reading in images seems problematic."

**Comment by jimjam-slam** [comment]
Thanks very much! I actually solved this on my end using an R script to
isolate the images that were landscape, rotating them and then manually
recomputing the feature coordinates in RectLabel's XML output. I don't
actually know what the EXIF orientation tags in the images are in my
images, but given your explanation of the way RectLabel's Resize All Images
works and the fact that it didn't alter my images, I think it's likely
they were all already front-oriented and it was just that the front in some
of them was landscape and in others it was portrait.

Thanks again!

*James Goldie*
Data scientist + climate/health researcher + developer
Email: ***@***.***
Phone: +61 3 9903 2102 <61399032102>, +61 421 747 208 <+61421747208>
Skype: james-goldie
Twitter: @jimjam_slam <http://twitter.com/jimjam_slam>

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by sahil-plutus** [comment]
s

**Comment by sahil-plutus** [comment]
![1_croped](https://github.com/ryouchinsa/Rectlabel-support/assets/100290349/8e6912ed-f30b-4402-b1a3-bab53bbb3709)
