### ISSUE TITLE
Slow image scrolling in macOS Monterrey on M1 Pro MacBook

### ISSUE THREAD

**Issue by law826** [ryouchinsa/Rectlabel-support#189]
I just upgraded to a new computer and the scrolling for Rectlabel seems to be very slow. I wasn't sure if this was due to the new operating system or the M1 architecture. Going from one image to the next used to be very smooth.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
In our environment, MacBook Pro M1 2020 + macOS Monterey, RectLabel apps are working well.
We can change the current image to the next or previous image smoothly.
To reproduce the problem, could tell us the details?

**Comment by law826** [comment]
Thanks for your response. I am using macOS Monterey V12.0 on a MacBook Pro 16-inch 2021 with M1 Pro chip. 

It seems like it is very slow when viewing images for the first time, but faster after the first viewing:
https://www.loom.com/share/b7338ae26ca34d9f8c7c7d942f08d9a2

**Comment by ryouchinsa** [comment]
Thanks for the detailed video.

We could reproduce the hotkeys disappearing problem and could fix in our environment.
We really appreciate your feedback.

For changing images problem, let us ask you some questions.

The first image is shown immediately.
1. You mean that it takes time to change the current image to next or previous image since you pressed right or left key?
2. Images and annotations are located on iCloud or other cloud storage?
3. If you could send a few images to support@rectlabel.com, it would be very helpful to reproduce the problem in our environment.

**Comment by law826** [comment]
1. Correct. Sometimes about a second to go from one image to the next. We review 100,000s of images, so fast scrolling is important to us. 
2. The images and annotations are synced to local before opening. 
3. Yes. Images will be sent.

**Comment by ryouchinsa** [comment]
Thanks for sending example images.

We could not reproduce the same problem on our MacBook Pro 13-inch, M1, 2020 + macOS Monterey 12.0.1.

How about clean installing RectLabel again.

1. Export the current settings file from the top menu bar, RectLabel => Export settings file.
2. Find and delete RectLabel cache folder in "~/Library/Containers".
3. Delete RectLabel app via the Launchpad app
4. Install RectLabel from Mac App Store.
5. Import the exported settings file from RectLabel => import settings file.

To have the same environment as you have, could you send the settings file to support@rectlabel.com?

For the hotkeys buttons disappearing problem, we submitted the new update to Apple today.

**Comment by law826** [comment]
I'm not sure what happened, but things started scrolling properly at this point without much intervention. I will follow your instructions if the problem arises again. Thanks for your support!

**Comment by ryouchinsa** [comment]
Thanks for your feedback.
If you have any other problems, please let us know.

The new update version 3.06.8 was released.
To show the new update on Mac App Store, press command + R to reload.

Added "Auto copy from previous image" on Label fast tab on the settings dialog.
Fixed the Hotkeys buttons disappearing problem on macOS Monterey.
Improved so that when you undo deleting polygons, polygon selections are restored.
