### ISSUE TITLE
What are the chances that you can open the source base?

### ISSUE THREAD

**Issue by dhushon** [ryouchinsa/Rectlabel-support#19]
Would like to make some improvements:

specifically build in a translator so that the annotation files/file can better be transcoded to the different project bases - like tensor box..

1) translate all annotations from json to P.voc
2) support relabelling annotations for simplification (again full set)
3) concatenate json files to a single annotation.json file (similarly for P.VoC)

Very willing to code improvements and drive Pos

**Comment by ryouchinsa** [comment]
We had another request for opening the source base. https://github.com/ryouchinsa/Rectlabel-support/issues/6

At this moment, RectLabel is a free app.
But in the future we are planning to add some premium features to monetize this app.
We think the labeling app could be like a productive software such as Adobe Photoshop and Illustrator.

> translate all annotations from json to P.voc
This means you annotated labels for some images in the JSON format.
But the format does not correspond to the tensorflow tools so that you need a converter.
The converter should run for multiple folders.

> support relabelling annotations for simplification (again full set)
What does this mean?

> concatenate json files to a single annotation.json file (similarly for P.VoC)
This means you want to concatenate the annotation file into a file and you want to read and modify the concatenated file on RectLabel.

Do you think RectLabel need the JSON format?
The Pascal VOC format might be enough.

Could you show us the example of the concatenated P.VoC format?

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

If you could code the converter by yourself and make it public on your Github repository, we would introduce your repository as one of the useful converters on our Github support page.

We added "Useful converters coded by our users".
https://github.com/ryouchinsa/Rectlabel-support

That would make sense because other users could use your converter and appreciate your work.
Let us know your opinion.

Best regards,
Ryo
