### ISSUE TITLE
Can it just transform the annotation formats?

### ISSUE THREAD

**Issue by Michael-FangJi** [ryouchinsa/Rectlabel-support#198]
Can it import one format and export to another?
e.g., import image folder with coco format and then export them to voc format?
thanks.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

In the latest version 37, you can import COCO 2017 dataset to RectLabel so that the COCO JSON file is converted to PASCAL VOC xml files.

COCO 2017 dataset.
https://cocodataset.org/#download

RectLabel has several export/import features.
https://rectlabel.com/help

Let us know your opinion.

![スクリーンショット 2022-04-25 5 50 37](https://user-images.githubusercontent.com/1954306/164996374-124531a3-c51e-4b0b-945b-235fb655bb88.png)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
