### ISSUE TITLE
Can't save bbox files

### ISSUE THREAD

**Issue by Elizabethcase** [ryouchinsa/Rectlabel-support#2]
Hey!

Can't seem to save BBox file on MacOS Sierra, RectLabel downloaded from the app store. Error says a folder can't be created but doesn't give another option for saving the .json (in my case) file, nor does making my own annotations folder fix the problem. 

Cheers,
Elizabth

**Comment by ryouchinsa** [comment]
Thanks for reporting the problem.

We think it is caused by the folder permissions.
We could reproduce the problem like this.

1. Put an image folder on our desktop
/Users/ryo/Desktop/images_test
2. Change the folder permissions using Mac Terminal
chmod -R 555 images_test
3. Open RectLabel, create a box, tries to save, and the error dialog appears.

![1](https://user-images.githubusercontent.com/1954306/27459048-52cc910e-57e7-11e7-94ef-bc9475ae3b13.jpg)

4. Change the folder permissions using Mac Terminal
chmod -R 755 images_test
5. Open RectLabel, create a box, tries to save, and it succeeds to create the annotations folder.

Could you check the permissions of the folder which you opened on RectLabel using Mac Terminal?
ls -la

We added the test images on this support page.
https://github.com/ryouchinsa/Rectlabel-support/tree/master/images_test

You could put this folder on to your desktop or home directory and check whether it works.

These images were downloaded from Unsplash so that images copyright is clear.
https://unsplash.com/

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
We think there is a problem when the folder path includes spaces. #7 
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update was released.
RectLabel 1.28
Fixed the problem when you open a folder which includes spaces.

**Comment by janecummings** [comment]
hi there! I am experiencing the same problem initially described in this issue. 

When I attempt to save an annotated image, a pop up instructs me to "Open a folder to load images. Click the "Open folder" button on the upper-left corner". I do so and select the current folder. Then an error pops up that says "Cannot save bookmark to the folder" and I lose the annotations on the image. 

It does not seem to be a permissions problem and there are no spaces in the path.

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

We cannot reproduce this problem in our environment so that we need your cooperation to fix this problem.

This error could happen when you open the folder and our program tries to obtain accessibility to the folder.

This api returns the error.
https://developer.apple.com/documentation/foundation/nsurl/1417795-bookmarkdatawithoptions

We call this api with the folder path you opened.

`NSURL* url = [NSURL URLWithString:folderPath];`
`bookmark = [url bookmarkDataWithOptions:...`

Could you tell us the folder path you tried to open?

Best regards,
Ryo
