### ISSUE TITLE
Inconsistent naming in XML and JSON formats

### ISSUE THREAD

**Issue by dhushon** [ryouchinsa/Rectlabel-support#29]
There are a number of inconsistencies in XML and JSON formats that range from the treatment of image size:
XML = 
 <size>
   <width>4928</width>
   <height>3280</height>
 </size>
JSON = "image_w_h" : [4928,3280],

to Objects:
XML = 
<object>
   <name>carconenumber-1</name>
   <bndbox>
     <xmin>2287</xmin>
     <ymin>1865</ymin>
     <xmax>2677</xmax>
     <ymax>2099</ymax>
   </bndbox>
 </object>

JSON = "objects" : [
 {
 "label" : "carconenumber-1",
 "x_y_w_h" : [2287, 1865, 391, 235]
}]

as well as challenges with respect to a concatenated annotation model supported for platforms like TensorBox.

The VOC format really expects:
/* tensorbox annotation format:
 https://github.com/Russell91/TensorBox/blob/master/utils/annolist/readme.md
 {
 "images": [image],
 "classes": [string]
 }
 
 image{
 "id": int,
 "image_path": string,
 "rects": [rect]
 }
 
 rect{
 "classID": int,
 "x1": int,
 "y1": int,
 "x2": int,
 "x2": int
 }*/

so there may be some "custom" Tensorflow semantics here, but I'd love to create the encoders/decoders to support a multitude of different TF annotation structures?

open the base?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

If you could code the converter by yourself and make it public on your Github repository, we would introduce your repository as one of the useful RectLabel tools on our Github support page.
https://github.com/ryouchinsa/Rectlabel-support

That would make sense because other users could use your tool and appreciate your work.

Let us know your opinion.

Best regards,
Ryo
