### ISSUE TITLE
No longer supporting conversion to JSON format

### ISSUE THREAD

**Issue by Wingspear** [ryouchinsa/Rectlabel-support#33]
Rectlabel can only convert to XML format and does not support conversion to JSON anymore. Also support for conversion to Kitti format for NVIDIA Digits would be great as well.

**Comment by ryouchinsa** [comment]
Hi, you can this converter.
Converter to the KITTI format on Nvidia DIGITS https://github.com/softwaremill/detectnet-tests

**Comment by cipri-tom** [comment]
Hello,

I have previously generated a lot of annotations in JSON format, which are no longer rendered by the new version. Please consider supporting the previous JSONs, or at least offer the possibility to keep the old version of RectLabel. I have updated it along with other programs, without realising it will break support

Thank you !

**Comment by ryouchinsa** [comment]
Hi,

Some users have troubles for the JSON format because the format cannot be used in TensorFlow directly.
There are many converters from the PASCAL VOC format to other formats.
So that we decided to focus on the PASCAL VOC format.
https://github.com/ryouchinsa/Rectlabel-support/issues/31

From File menu, you can convert the JSON files to XML files in the folder.
https://rectlabel.com/help

![unnamed](https://user-images.githubusercontent.com/1954306/33556045-fac258c8-d945-11e7-8ce1-da115dfe5cf7.png)

We are sorry for your inconvenience.

**Comment by cipri-tom** [comment]
Hi,

Thank you for the fast reply.
I have already built processes for working with the JSON that was made and extended it. I understand that the PASCAL VOC is popular, but here you had the chance to actually establish a new norm, since XML is old and difficult to work with.

Given that I do not need the latest features, is there a way to downgrade to the previous version ?
Thank you !

**Comment by ryouchinsa** [comment]
We understand you have to change your code to use the XML format.
Some other users contacted us and they could understand the reason.

The most popular image annotation tool "LabelImg" is focusing on the XML format.
https://github.com/tzutalin/labelImg

The most important thing for us is to stop issues report about the output format.
So that we could focus on the new feature requests along with the new papers such as box rotation and polygon-based image segmentation.
Hopefully you could understand.

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
Now you can "Export XML files to KITTI txt files".
https://rectlabel.com/help#xml_to_kitti

```
type(1) truncated(1) occluded(1) alpha(1) bbox(4) dimensions(3) location(3) rotation_y(1)
person 0.0 0 -1 174.0 367.0 423.0 602.0 -1 -1 -1 -1 -1 -1 -1
```
