### ISSUE TITLE
About bounding box rotation

### ISSUE THREAD

**Issue by Zico2017** [ryouchinsa/Rectlabel-support#35]
1. After rotating the bounding box, we can't change the size of bounding box with keeping the shape of it as a rectangular. Could you add some constraints?
2. A possible improvement is to provide more output format: like (center_point_x,center_point_y,width,height,rotation_angle) in xml

Anyway, your tool is the most convenient to use for OSX users, thank you!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We are going to improve editing the rotated box and the format.

Could you tell us which object detection tool are you going to use with the format?
Because we want to know which format would be the best for the rotated box to connect to other tools.

Best regards,
Ryo

**Comment by Zico2017** [comment]
A very prompt reply!

I only find two papers which use the format based on the code of faster r-cnn, it looks 5 variables to label a rotated bounding box is better than 8 variables. 
Arbitrary-Oriented Scene Text Detection via Rotation Proposals (https://github.com/mjq11302010044/RRPN)
Learning a Rotation Invariant Detector with Rotatable Bounding Box 
(https://github.com/liulei01/DRBox)

Looking for your next version!

**Comment by ryouchinsa** [comment]
Thanks for letting us know those tools.

We could find the proposed format in "Arbitrary-Oriented Scene Text Detection via Rotation Proposals ".

![1](https://user-images.githubusercontent.com/1954306/36483999-302cbfe6-175b-11e8-9a92-878b298fc1a6.png)

We would let you know when we submit the new update.

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
The new update version 1.81 was released.

- Added constraints to the rotated boxes so that you can edit the size with keeping the shape of it as a rectangular.
- Changed the newly created rotated box format.
The rotated box is saved in the format as (center_x, center_y, width, height, rotation).
The rotation is ranged between 0 and 2Pi.
RectLabel can read and edit the existing rotated boxes as polygons.

![out](https://user-images.githubusercontent.com/1954306/36629054-1c29826e-1994-11e8-97aa-37c8b42710e7.gif)

![2](https://user-images.githubusercontent.com/1954306/36627759-e678e46a-198a-11e8-849f-766faf021140.png)

https://rectlabel.com/help

Let us know your opinion.

**Comment by violet-day** [comment]
@ryouchinsa could you please share the code `rotated_box` how to convert to `polygon`
 
I was annotate samples use rotated_box

The model I pick use `ICDAR2015` format like `377,117,463,117,465,130,378,130,Genaxis Theatre`

**Comment by ryouchinsa** [comment]
Hi,

This is how you could convert the rotated box to the polygon points.

```
cos = cos(rot);
sin = sin(rot);

x1 = -width / 2;
y1 = -height / 2;
x1 = cx + x1 * cos - y1 * sin;
y1 = cy + x1 * sin + y1 * cos;

x2 = width / 2;
y2 = -height / 2;
...
```

**Comment by ryouchinsa** [comment]
In the latest version 2025.11.16, we added "rotated box" to the Create polygon using SAM.

<video src="https://github.com/user-attachments/assets/f5b2d9f6-dba6-4a56-acb6-8c71206a55a9" controls="controls" muted="muted" class="width-fit" style="max-height:640px; min-height: 200px"></video>

When principal component analysis does not recognize the correct orientation.

<video src="https://github.com/user-attachments/assets/ec7e3f6f-1da9-4ae2-8c9d-a52be252f5b6" controls="controls" muted="muted" class="width-fit" style="max-height:640px; min-height: 200px"></video>
