### ISSUE TITLE
Cannot save bookmark to the folder

### ISSUE THREAD

**Issue by tynetom** [ryouchinsa/Rectlabel-support#42]
The file couldn't be opened.

file:///Users/.....

I'm getting this error message whenever I try to open a folder, same message whether it is a folder that I've already annotated in Rectlabel (with existing xml files) or a new one.  Haven't used the app in a couple of months but was working well before

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

When you open a folder, we try to save the access right to read/write in the folder.
But the api "bookmarkDataWithOptions" returns "The file couldn't be opened" error.
https://developer.apple.com/documentation/foundation/nsurl/1417795-bookmarkdatawithoptions?language=objc

We have a few reports of the problem from our users and they said the problem solved in a month.

- Yesterday when I tried again after some weeks, the error is not appearing. I did not do anything besides what you told me to clean some folders (but I did this weeks ago not recently), so I really don’t know what could have solved the issue. 

- Sorry for the late response. The issue was resolved after upgraded to the latest RectLabel.

- Clearing RectLabel's cache files
Export Settings File from File menu and remove the folder below.
~/Library/Containers/com.waysify.roi/

We talked with apple technical support involving a few users but we could not know what was the essential reason to cause the problem.
https://developer.apple.com/support/technical/

> Haven't used the app in a couple of months but was working well before

There might be an expiration date for the bookmark.
If we discard the old bookmark created more than a week ago and let users open the folder again, the problem might not happen.

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
Hi, thanks for reporting the issue.
Could you tell us the RectLabel version and the OS X version?

**Comment by icicle4** [comment]
The RectLabel version is Version 1.96 (1.96),
and my system version is OSx10.13.3 (17D47).

**Comment by ryouchinsa** [comment]
Thanks for the information.

If you could, could you zip RectLabel app and send it to us?
support@rectlabel.com

We can check whether it works or not in our environment.

**Comment by ryouchinsa** [comment]
Our user solved the problem using the method below.
https://support.omnigroup.com/troubleshooting-mas-downloads/

This would help you to reinstall RectLabel in a clean way.
