### ISSUE TITLE
Feature request: Direct export to Turi Create?

### ISSUE THREAD

**Issue by bysnrk** [ryouchinsa/Rectlabel-support#43]
Great app!

Would like it to export direct to Turi Create format. I know CSV export is implemented, but would be nice with a export for Turi button.

If you could do a smooth transition from pictures to Turi, I could easily see your app becoming a 'standard app' in the workflow of marking images for machine learning on macOS.

Thats all, have a nice day!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Currently we are using the Turi Create python api to save the sframe file.
We would check if we could save in the sframe format from Objective-C code.

Introduction to SFrames
https://github.com/apple/turicreate/blob/master/userguide/sframe/sframe-intro.md

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
We searched the way how to save sframe file from Objective-c code directly.
Turi create has an experimental C++ API but there are not enough sample code.
So that at this moment, to realize your feature request is difficult for us.
Hopefully you could understand.

Using the C++ API (Experimental)
https://apple.github.io/turicreate/docs/userguide/cpp.html

Example of C++ API usage
https://github.com/apple/turicreate/issues/211

It might be worthwhile to give several different examples, that show a larger span of our most common APIs - such as read_csv(), save()\load(), apply() etc
https://github.com/apple/turicreate/pull/271

A significant amount of logic in the read_csv function of SFrame is implemented in python and thus inaccessible through the C-API. This logic should be moved to a consistent place in C++.
https://github.com/apple/turicreate/issues/812
