### ISSUE TITLE
Order of image 

### ISSUE THREAD

**Issue by JudyMRSD** [ryouchinsa/Rectlabel-support#44]
Hello, looks like the images are ordered as "339.jpg, 3390.jpg, 3391.jpg, ....". Is there a way I can order images by the numerical value instead of alphabetical order? I was trying to get images in the order "339.jpg, 340.jpg, 341.jpg ...". Thanks a lot!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We modified our logic so that If the filename is numeric, the filename is compared numerically.
In the next update, this feature would be released.

Current order:
![before](https://user-images.githubusercontent.com/1954306/42728671-9b7cccf4-87fa-11e8-9c68-aff27168dc5e.png)

New order:
![after](https://user-images.githubusercontent.com/1954306/42728672-9ec2b8e2-87fa-11e8-9762-235e1689be4f.png)

Best regards,
Ryo

**Comment by JudyMRSD** [comment]
Thank you very much for creating this awesome app and adding this new feature!

**Comment by ryouchinsa** [comment]
Hi, the new update version 1.99 was released.

**Comment by JudyMRSD** [comment]
Thank you very much! It works perfectly now!
