### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by MrOCR** [ryouchinsa/Rectlabel-support#54]
Can you release a linux or windows version?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We know the windows and linux versions are needed by our users.

![2018-10-07 0 52 25](https://user-images.githubusercontent.com/1954306/46573103-47814b80-c9cb-11e8-9e5e-bab0c379815f.png)

Currently we are a small team so that focusing on the macOS app.

Best regards,
Ryo

**Comment by MrOCR** [comment]
@ryouchinsa
