### ISSUE TITLE
Convert to tfrecord, training, evaluation, test

### ISSUE THREAD

**Issue by nathanaherne** [ryouchinsa/Rectlabel-support#62]
I have been going through all the Tensorflow Object API code and noticed that [one of the scripts supplied with tensorflow models](https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py) split the data into train, test, validation tfrecord datasets. I realise that you can shuffle and split the tfrecord data when you are training the model, so adding this feature isn't a deal breaker. In saying this, it may be a useful to be able to instruct the rectlabel_create_pascal_tf_record.py script to split the data into train, validation, test datasets (with a corresponding percentage for each). It may help newcomers to ML to more easily follow the current tutorials on the web.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

In the code for the PASCAL VOC XML files, there is a list for splitting the data.
https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py
```
SETS = ['train', 'val', 'trainval', 'test']
```
they are assuming that 4 text files are created that describe which image should belong to which set.
Currently RectLabel does not have the feature to create this file.

In the code for the COCO JSON file, you can split data in the python code.
https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_coco_tf_record.py
```
_create_tf_record_from_coco_annotations(
      FLAGS.train_annotations_file,
      FLAGS.train_image_dir,
      train_output_path,
      FLAGS.include_masks,
      num_shards=100)
_create_tf_record_from_coco_annotations(
      FLAGS.val_annotations_file,
      FLAGS.val_image_dir,
      val_output_path,
      FLAGS.include_masks,
      num_shards=10)
_create_tf_record_from_coco_annotations(
      FLAGS.testdev_annotations_file,
      FLAGS.test_image_dir,
      testdev_output_path,
      FLAGS.include_masks,
      num_shards=100)
```

Our code is following this so that you can split data into "train" and "val".
You can extend this code very easily.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/rectlabel_create_coco_tf_record.py

To convert you PASCAL VOC XML files to COCO JSON file, you can use "Export XML files to COCO JSON file" feature.

Let us know your opinion.

**Comment by ryouchinsa** [comment]
Hi,

We would add the feature to create train.txt, val.txt, and test.txt.
Those text files have lines of annotation file name prefix.
0
1
2
...

We would update our sample python code, too.
When the new update is available, we would let you know.

Best regards,
Ryo

**Comment by nathanaherne** [comment]
Hi,

I like your idea, it would be great to be able to provide that information at the command line like --split "60/40" which would create one file with 60% of the images and one with 40% of the images. For more files you could use --split "60/20/20", which would create three files.

What would the text files contain? What would be the process to create tfrecords from the text files?

**Comment by ryouchinsa** [comment]
Again, the text file contains lines of the xml file name prefix which does not include ".xml".

It is totally the same format as being used on tensorflow's python code.
https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py

If you want to know the details, download the VOC 2007 data.
http://host.robots.ox.ac.uk/pascal/VOC/voc2007/

The process to create tfrecords:
- RectLabel creates xml files and text files to split into train, val, and test.
- Our python code creates tfrecords from the xml files and text files.

We would update our python code so that our python code accepts the text files to split into train, val, and test.
It would be the same process to use the tensorflow's original python code.
https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py

**Comment by nathanaherne** [comment]
Thank you for your answer. 

One more question - would RectLabel create the text files based on some metric the user specified (which I assume are just comma separated entries) from the script, from the program or would the user need to write code to create them?

**Comment by ryouchinsa** [comment]
We would accept your user input to split the data into train, val, and test.

If we implemented on RectLabel, it would be text boxes.
If we implemented on python code, it would be command line arguments.

**Comment by ryouchinsa** [comment]
We added the split data feature into our python code.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/rectlabel_create_pascal_tf_record.py
```
python object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py \
    --images_dir="${IMAGES_DIR}" \
    --label_map_path="${LABEL_MAP_PATH}" \
    --output_dir="${OUTPUT_DIR}" \
    --split_rates="${SPLIT_RATES}" \
    --split_names="${SPLIT_NAMES}" \
    --include_masks
flags.DEFINE_string('output_dir', '', 'Directory to output TFRecord')
flags.DEFINE_string('split_rates', '60/20/20', 'Split data into train, val, test')
flags.DEFINE_string('split_names', 'train/val/test', 'Split data into train, val, test')
```

**Comment by nathanaherne** [comment]
Thank you, I will test this out once the Mask stuff is available.

**Comment by ryouchinsa** [comment]
Now you can "Export train, val, and test.txt" on RectLabel.
https://rectlabel.com/help#split_images

The python code to export TFRecord for Tensorflow was updated.
https://rectlabel.com/help#tf_record
