### ISSUE TITLE
Feature Request - Add ability to import object labels from web API

### ISSUE THREAD

**Issue by hohonuuli** [ryouchinsa/Rectlabel-support#80]
Currently the list of label's in RectLabel are manually edited. We have a web API endpoint at <http://dsg.mbari.org/kb/v1/concept> that produces a list of terms that we use for our image and video annotation systems. A nice-to-have feature would be to add a button that allows users to enter a URL which produces a simple JSON array of terms, and have those terms added as object labels in Rectlabel. 

![screen shot 2019-01-31 at 9 45 21 am](https://user-images.githubusercontent.com/282941/52074046-dea37d80-253d-11e9-8917-061b3ebb5f1d.png)

**Comment by ryouchinsa** [comment]
Thanks for writing the feature request.

We would develop the prototype.

Do you want to add objects to the objects table or replace the current objects table with the content from the web api?

**Comment by ryouchinsa** [comment]
> Allow users to both export and load existing lists of object labels to/from a file. 

Though we are providing both exporting and importing the settings file, 
you need the same interface for the objects table of the current project.

For exporting and importing the objects table, we can provide those features.
Now we have "Export names for YOLO" in the File menu.
https://rectlabel.com/help#yolo_names
Exporting the objects table would have the same data format.
```
car
plate
person
dog
```
In the App menu, there are "Export settings file" and "Import settings file".
For the UI/UX simplicity, we can add "Export objects table" and "Import objects table" there.
We think opening another dialog on the settings dialog would not be the best in terms of UI/UX design.
Let us know your opinion.

> Importing from a file or API endpoint would add to the existing object labels.

We could understand it adds the content and not replaces the content.
We can add "Import objects table through API" feature which opens the dialog where you can input the API url.
```
Export settings file
Import settings file
Export objects table
Import objects table
Import objects table through API
```

> Add a method (button) to allow users to clear all terms from the existing list.

Now using right clicking, you can "Sort Alphabetic" the objects table.
We can add "Clear objects table" here.
On the settings dialog, we are not providing the Control + Z function.
So that we are afraid that our users accidentally clear the objects table.

Again, what we care about is opening another dialog on the settings dialog would not be the best.
If we could come up with the better UI/UX idea, we can change in the future.
Let us know your opinion.

> We have this type of filtering built into our video annotation tools. I can try to pull together a quick video to demo it if needed.

You mean the auto suggestion feature.
Could you show us the video or gif animation how it works for your objects list?

**Comment by ryouchinsa** [comment]
The new update version 2.46 was released.

- Added "Export objects table" on App menu.
- Added "Import objects table" on App menu.
- Added "Import objects table through API" on App menu.
- Added "Clear objects table" on the objects table header. Right clicking on the header would show the menu.
- Auto-suggest speeds up selecting the object name.
- Improved the draw speed using the object index table and not to calculate each object index using string matching every frame.
- Improved the save speed for the settings labels file.

We think RectLabel could work with more than 5000 objects now.
Let us know your opinion.

![2019-02-12 22 09 45](https://user-images.githubusercontent.com/1954306/52637872-e981e900-2f13-11e9-973a-025f8e2319af.png)

![2019-02-12 22 21 44](https://user-images.githubusercontent.com/1954306/52638140-99575680-2f14-11e9-924c-3a543fe1cbc5.png)

![2019-02-12 22 18 10](https://user-images.githubusercontent.com/1954306/52637950-1cc47800-2f14-11e9-9cb5-5b5530f60ffd.png)

![2019-02-12 22 15 13](https://user-images.githubusercontent.com/1954306/52637812-b4759680-2f13-11e9-8570-69c62d9ed5e3.png)

![auto_suggest](https://user-images.githubusercontent.com/1954306/52637663-35805e00-2f13-11e9-8986-100d603c056c.gif)

**Comment by hohonuuli** [comment]
Fantastic! I've forwarded this issue on to our machine learning teams so that they know to look for it. Thanks for adding this feature.
