### ISSUE TITLE
Add search box or autocomplete to label dialogue

### ISSUE THREAD

**Issue by lonnylundsten** [ryouchinsa/Rectlabel-support#82]
When adding labels, having a search box or autocomplete for objects would greatly speed up labeling of images. This might be implemented by only allowing objects to be added to the object list through the import methods or only within the preferences (so you can't add new ones in the label window) and then the label window is a searchable list with autocomplete. For long object lists, the drop down list is not practical.

Thank you!

![screen shot 2019-02-13 at 8 51 54 am](https://user-images.githubusercontent.com/32526132/52728792-cc2d3900-2f6c-11e9-8292-d43e21a73060.png)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

The total number of your objects is more than 5000.
When you open the label dialog and click on the "Objects" pop-up button, it shows 5000 objects.
So that before selecting, you have to start texting the prefix to reduce the number of items.

When you start texting the prefix of the object name on the label dialog, our auto-suggests reduces the number of items in the "Objects" pop-up button.
So that you can select from much fewer items.
In the example image, when you text "crab" on the text box, the number of items reduced from 5000 to about 20.
This would be very comfortable for your annotators.

Did you try the new auto-suggest feature?
Let us know the difference between the new auto-suggest feature and your "search box or autocomplete" feature.

![2019-02-14 2 24 58](https://user-images.githubusercontent.com/1954306/52730926-d77d7480-2fff-11e9-9d3e-0b7c8a52caff.png)

**Comment by lonnylundsten** [comment]
Ryo - Thanks!.= I haven't tried it yet but will as soon as I get a chance and let you know how it works for us.
Lonny

**Comment by ryouchinsa** [comment]
In the version 3.00.6, we improved the auto suggestions on the label dialog.

![auto_suggestions](https://user-images.githubusercontent.com/1954306/75540377-44bf4480-5a5f-11ea-8ce0-65511a39967b.gif)

Using "Close label dialog when select", you can skip clicking the OK button.
https://rectlabel.com/help#label_fast

![auto_suggestions_skip_ok](https://user-images.githubusercontent.com/1954306/75540386-48eb6200-5a5f-11ea-93b5-8a38200245f5.gif)
