### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by klainkaliber** [ryouchinsa/Rectlabel-support#86]
Hi,
do you have a plan for releasing a Windows version of Rectlabel?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Every month more Windows users are visiting our website than macOS users.
https://github.com/ryouchinsa/Rectlabel-support/issues/54

We understand there is a need for the Windows version but we do not have enough resource to develop it.

From medical companies, the iPad version is being requested.
iOS and macOS are kind of similar platform so that we are developing the iPad version.
https://github.com/ryouchinsa/Rectlabel-support/issues/70
