### ISSUE TITLE
Load pre-annotated mask for correcting points

### ISSUE THREAD

**Issue by malwayson** [ryouchinsa/Rectlabel-support#87]
Can I load pre-annotated png masks along with raw images for correcting the segmentation masks...?
I have tried to load the images and mask files but the mask files are loaded as normal images..

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

This is how to import pixels.
https://rectlabel.com/help#import_pixels

If this could not solve the problem, let us know the example image, mask image, and xml file.

**Comment by alelordelo** [comment]
Hi, on the link I didn’t find how to import masks as pixels

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
We apologize that the web link has changed.
http://rectlabel.com/edit#create_pixels

Right clicking on the pixels, the "Import pixels" menu appears.

![スクリーンショット 2023-05-25 15 05 27](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/6d615efa-fa8a-4f72-825c-2ef8534172db)

**Comment by ryouchinsa** [comment]
Improved so that you can drag & drop grayscale mask images to the labels table.
The new version 2023.05.29 was released.

![dragDropToLabelsTable](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/0f1d6055-444b-4fca-aa00-45344521c39c)

**Comment by ryouchinsa** [comment]
Improved so that you can drag & drop the COCO RLE JSON file of the SA-1B dataset to the labels table to import mask annotations.
The new version 2023.05.31 was released.

Segment Anything 1 Billion (SA-1B) is a dataset designed for training general-purpose object segmentation models from open world images.
https://github.com/facebookresearch/segment-anything

![dragDropRLEJSONFilesXML](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/c15b6458-9dfa-44f1-94e7-320e306a4554)
