### ISSUE TITLE
new version converts a - in label name to _

### ISSUE THREAD

**Issue by romanoss** [ryouchinsa/Rectlabel-support#93]
...which leads to errors in eg xml to coco json export

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

On RectLabel, "-" is  converted to "_".

> The label "sneakers-yellow-converse-right" is a combination of the object and attributes.
"-" is used as a separator so that "-" in the object name and attribute name would be converted to "_".
https://rectlabel.com/help#attributes

Could you show us the detailed situation when you have the error caused by the conversion?

We add an object name "teleport-skill-button" to our object table.
When we label, it is labeled as "teleport_skill_button".
When we "Export XML files to COCO JSON file", there is no errors.

**Comment by romanoss** [comment]
I do not use attributes but only labels/objects and I use - as part of my label/object name. One week ago the - was not changed and was a - in the rectlabel xml file. Now its converted to a _

I am not sure if it harms.

When I do 'Export XML files to YOLO text files' or 'Export XML files to COCO JSON file' I get an error/warning ? box saying 'Label names are not found on objects table -  We need the object index to export'. Probably because the object name still has the - and the lable name has the _


I think its not a problem for YOLO.txt (which has the - in the export labels) but I don't know about the rules for COCO JSON.

**Comment by ryouchinsa** [comment]
To start with RectLabel, you have to set up your objects table.

![スクリーンショット 2019-04-10 9 56 59](https://user-images.githubusercontent.com/1954306/55844453-41397b00-5b78-11e9-8dd9-dc50bca3ebf1.png)

That warning dialog means there are some labels which are not added on the objects table.

Do you have empty string labels In your xml files?
Change the empty string to another one and add the new label name on the objects table.

**Comment by romanoss** [comment]
>Do you have empty string labels In your xml files?

I had 1 -thanks.
